"""Init

Revision ID: 27f45fc6901b
Revises: 
Create Date: 2022-04-19 17:15:16.558370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27f45fc6901b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('citizen',
    sa.Column('citizen_id', sa.Integer(), nullable=False),
    sa.Column('town', sa.String(), nullable=False),
    sa.Column('building', sa.String(), nullable=False),
    sa.Column('apartment', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('gender', sa.Enum('FEMALE', 'MALE', 'NOT_MENTIONED', name='gender'), nullable=False),
    sa.PrimaryKeyConstraint('citizen_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('citizen')
    # ### end Alembic commands ###
